### PR TITLE
unite pre-commit and CI linting

### PR DESCRIPTION
**Pull request by christophlohrmann**
... to make sure that the two always use the same version of black, isort, ...

### CODE REVIEW

**Review by SamTov — APPROVED** [review]
Happy with it

**Comment by christophlohrmann** [comment]
don't merge. This isn't working correctly yet

**Comment by SamTov** [comment]
> should we keep the auto-fix or should I try to disable it?

I actually like it.

**Comment by SamTov** [comment]
The linting rules need to be removed from the branch rules for this to pass I think.

**Comment by christophlohrmann** [comment]
then this is good to go once it's all green

**Comment by SamTov** [comment]
> The linting rules need to be removed from the branch rules for this to pass I think.

Took care of it

**Pull request merged**
